# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

localfci_cpp <- function(true_dag, df, targets, names, lmax = 3L, signif_level = 0.01, verbose = TRUE) {
    .Call(`_LocalFCI_localfci_cpp`, true_dag, df, targets, names, lmax, signif_level, verbose)
}

localfci_cpp_pop <- function(true_dag, targets, names, lmax = 3L, verbose = TRUE) {
    .Call(`_LocalFCI_localfci_cpp_pop`, true_dag, targets, names, lmax, verbose)
}

localpc_cpp <- function(true_dag, df, targets, names, lmax = 3L, signif_level = 0.01, verbose = TRUE) {
    .Call(`_LocalFCI_localpc_cpp`, true_dag, df, targets, names, lmax, signif_level, verbose)
}

localpc_cpp_pop <- function(true_dag, targets, names, lmax = 3L, verbose = TRUE) {
    .Call(`_LocalFCI_localpc_cpp_pop`, true_dag, targets, names, lmax, verbose)
}

sharedNeighborhood <- function(reference, targets, i, j, verbose = FALSE) {
    .Call(`_LocalFCI_sharedNeighborhood`, reference, targets, i, j, verbose)
}

inTargetNeighborhood <- function(reference, targets, i, verbose = FALSE) {
    .Call(`_LocalFCI_inTargetNeighborhood`, reference, targets, i, verbose)
}

compare_skeletons <- function(est, truth, targets) {
    .Call(`_LocalFCI_compare_skeletons`, est, truth, targets)
}

compare_v_structures <- function(est, truth, targets) {
    .Call(`_LocalFCI_compare_v_structures`, est, truth, targets)
}

parent_recovery_accuracy <- function(est, truth, targets, verbose = FALSE) {
    .Call(`_LocalFCI_parent_recovery_accuracy`, est, truth, targets, verbose)
}

interNeighborhoodEdgeMetrics <- function(est, reference, targets, verbose = TRUE) {
    .Call(`_LocalFCI_interNeighborhoodEdgeMetrics`, est, reference, targets, verbose)
}

overallF1 <- function(est, ref, targets, verbose) {
    .Call(`_LocalFCI_overallF1`, est, ref, targets, verbose)
}

all_metrics <- function(est, ref_graph, targets, verbose = FALSE, algo = "pc", ref = "sub_cpdag") {
    .Call(`_LocalFCI_all_metrics`, est, ref_graph, targets, verbose, algo, ref)
}

neighborhood_metrics <- function(G) {
    .Call(`_LocalFCI_neighborhood_metrics`, G)
}

getPartialCorrelation <- function(C, i, j, k) {
    .Call(`_LocalFCI_getPartialCorrelation`, C, i, j, k)
}

fisherZ <- function(pc, n, k_size) {
    .Call(`_LocalFCI_fisherZ`, pc, n, k_size)
}

condIndTest <- function(C, i, j, k, n, signif_level) {
    .Call(`_LocalFCI_condIndTest`, C, i, j, k, n, signif_level)
}

condIndTestPop <- function(G, i, j, k) {
    .Call(`_LocalFCI_condIndTestPop`, G, i, j, k)
}

combn_cpp <- function(x, l) {
    .Call(`_LocalFCI_combn_cpp`, x, l)
}

isMember <- function(x, i) {
    .Call(`_LocalFCI_isMember`, x, i)
}

testArmaCor <- function(M) {
    .Call(`_LocalFCI_testArmaCor`, M)
}

check_amat_works <- function(nodes, node_names, adj) {
    .Call(`_LocalFCI_check_amat_works`, nodes, node_names, adj)
}

check_amat_works_onepar <- function(nodes) {
    .Call(`_LocalFCI_check_amat_works_onepar`, nodes)
}

check_names_works <- function(nodes, node_names, adj) {
    .Call(`_LocalFCI_check_names_works`, nodes, node_names, adj)
}

check_dag_object <- function(nodes, node_names, adj) {
    .Call(`_LocalFCI_check_dag_object`, nodes, node_names, adj)
}

check_dag_object2 <- function(nodes) {
    invisible(.Call(`_LocalFCI_check_dag_object2`, nodes))
}

check_neighbors_retrieval <- function(nodes, node_names, adj, t) {
    .Call(`_LocalFCI_check_neighbors_retrieval`, nodes, node_names, adj, t)
}

check_amat_retrieval <- function(nodes, node_names, adj, i, j) {
    .Call(`_LocalFCI_check_amat_retrieval`, nodes, node_names, adj, i, j)
}

check_amat_retrieval_function <- function(nodes, node_names, adj, i, j) {
    .Call(`_LocalFCI_check_amat_retrieval_function`, nodes, node_names, adj, i, j)
}

check_amat_row_retrieval <- function(nodes, node_names, adj, i) {
    .Call(`_LocalFCI_check_amat_row_retrieval`, nodes, node_names, adj, i)
}

check_amat_col_retrieval <- function(nodes, node_names, adj, j) {
    .Call(`_LocalFCI_check_amat_col_retrieval`, nodes, node_names, adj, j)
}

check_adjacent_non_adjacent <- function(nodes, node_names, adj, i) {
    .Call(`_LocalFCI_check_adjacent_non_adjacent`, nodes, node_names, adj, i)
}

check_non_adjacent_solo <- function(nodes, node_names, adj, i) {
    .Call(`_LocalFCI_check_non_adjacent_solo`, nodes, node_names, adj, i)
}

check_amat_setval <- function(nodes, node_names, adj, i, j, val) {
    .Call(`_LocalFCI_check_amat_setval`, nodes, node_names, adj, i, j, val)
}

checkIfNeighbors <- function(nodes, node_names, adj, i, j) {
    .Call(`_LocalFCI_checkIfNeighbors`, nodes, node_names, adj, i, j)
}

checkEmptyGraph <- function(p) {
    .Call(`_LocalFCI_checkEmptyGraph`, p)
}

checkAcyclicity <- function(nodes, node_names, adj) {
    .Call(`_LocalFCI_checkAcyclicity`, nodes, node_names, adj)
}

checkIsAncestor <- function(nodes, node_names, adj, desc, anc) {
    .Call(`_LocalFCI_checkIsAncestor`, nodes, node_names, adj, desc, anc)
}

initializeLocalFCI <- function(td, df, t, names) {
    invisible(.Call(`_LocalFCI_initializeLocalFCI`, td, df, t, names))
}

initializeLocalFCIPop <- function(td, t, names) {
    invisible(.Call(`_LocalFCI_initializeLocalFCIPop`, td, t, names))
}

checkSkeletonTotal <- function(td, df, t, names) {
    .Call(`_LocalFCI_checkSkeletonTotal`, td, df, t, names)
}

checkSkeletonTotalPop <- function(td, t, names) {
    .Call(`_LocalFCI_checkSkeletonTotalPop`, td, t, names)
}

checkVStruct <- function(td, df, t, names) {
    .Call(`_LocalFCI_checkVStruct`, td, df, t, names)
}

checkVStructPop <- function(td, t, names) {
    .Call(`_LocalFCI_checkVStructPop`, td, t, names)
}

checkAdjMatConversion <- function(td, df, t, names, m, neighbors) {
    .Call(`_LocalFCI_checkAdjMatConversion`, td, df, t, names, m, neighbors)
}

checkSeparationTest <- function(td, df, t, names, i, j, l, nodes_to_skip) {
    .Call(`_LocalFCI_checkSeparationTest`, td, df, t, names, i, j, l, nodes_to_skip)
}

checkLocalFCISummary <- function(td, df, targets, names) {
    .Call(`_LocalFCI_checkLocalFCISummary`, td, df, targets, names)
}

checkLocalFCISummaryPop <- function(td, targets, names) {
    .Call(`_LocalFCI_checkLocalFCISummaryPop`, td, targets, names)
}

checkInitializeLocalPC <- function(td, df, t, names) {
    .Call(`_LocalFCI_checkInitializeLocalPC`, td, df, t, names)
}

checkGetTargetSkel <- function(td, df, t, names) {
    .Call(`_LocalFCI_checkGetTargetSkel`, td, df, t, names)
}

checkGetVStructures <- function(td, df, t, names) {
    .Call(`_LocalFCI_checkGetVStructures`, td, df, t, names)
}

checkInitializeLocalPCPop <- function(td, t, names) {
    .Call(`_LocalFCI_checkInitializeLocalPCPop`, td, t, names)
}

checkGetTargetSkelPop <- function(td, t, names) {
    .Call(`_LocalFCI_checkGetTargetSkelPop`, td, t, names)
}

checkGetVStructuresPop <- function(td, t, names) {
    .Call(`_LocalFCI_checkGetVStructuresPop`, td, t, names)
}

checkLocalPC <- function(td, df, t, names) {
    .Call(`_LocalFCI_checkLocalPC`, td, df, t, names)
}

checkLocalPCPop <- function(td, t, names) {
    .Call(`_LocalFCI_checkLocalPCPop`, td, t, names)
}

test_union <- function(x, y) {
    .Call(`_LocalFCI_test_union`, x, y)
}

test_sort <- function(x) {
    .Call(`_LocalFCI_test_sort`, x)
}

test_fill <- function(nrow, ncol, value) {
    .Call(`_LocalFCI_test_fill`, nrow, ncol, value)
}

test_fill_diag <- function(x, value) {
    .Call(`_LocalFCI_test_fill_diag`, x, value)
}

test_create <- function(x1, x2) {
    .Call(`_LocalFCI_test_create`, x1, x2)
}

test_setdiff <- function(v1, v2) {
    .Call(`_LocalFCI_test_setdiff`, v1, v2)
}

test_intersect <- function(v1, v2) {
    .Call(`_LocalFCI_test_intersect`, v1, v2)
}

test_map_insert <- function(v1, v2) {
    .Call(`_LocalFCI_test_map_insert`, v1, v2)
}

test_map_find <- function(v1, v2, a) {
    invisible(.Call(`_LocalFCI_test_map_find`, v1, v2, a))
}

test_sep_arma <- function() {
    .Call(`_LocalFCI_test_sep_arma`)
}

test_subset_mat <- function(m, i) {
    .Call(`_LocalFCI_test_subset_mat`, m, i)
}

test_NumMat_value <- function(G) {
    .Call(`_LocalFCI_test_NumMat_value`, G)
}

test_decrement_matrix <- function(G) {
    invisible(.Call(`_LocalFCI_test_decrement_matrix`, G))
}

testRule1 <- function(td, dummy_df, dummy_t, names, m) {
    .Call(`_LocalFCI_testRule1`, td, dummy_df, dummy_t, names, m)
}

testRule2 <- function(td, dummy_df, dummy_t, names, m) {
    .Call(`_LocalFCI_testRule2`, td, dummy_df, dummy_t, names, m)
}

testRule3 <- function(td, dummy_df, dummy_t, names, m) {
    .Call(`_LocalFCI_testRule3`, td, dummy_df, dummy_t, names, m)
}

testRule4 <- function(td, dummy_df, dummy_t, names, m, i, j, k) {
    .Call(`_LocalFCI_testRule4`, td, dummy_df, dummy_t, names, m, i, j, k)
}

testRule8 <- function(td, dummy_df, dummy_t, names, m) {
    .Call(`_LocalFCI_testRule8`, td, dummy_df, dummy_t, names, m)
}

testRule9 <- function(td, dummy_df, dummy_t, names, m) {
    .Call(`_LocalFCI_testRule9`, td, dummy_df, dummy_t, names, m)
}

testRule10 <- function(td, dummy_df, dummy_t, names, m) {
    .Call(`_LocalFCI_testRule10`, td, dummy_df, dummy_t, names, m)
}

testallRules <- function(td, dummy_df, dummy_t, names, m) {
    .Call(`_LocalFCI_testallRules`, td, dummy_df, dummy_t, names, m)
}

testConvertMixed <- function(td, t, names, m, v) {
    .Call(`_LocalFCI_testConvertMixed`, td, t, names, m, v)
}

getNbhd <- function(p, node_names, adj, targets, verbose) {
    .Call(`_LocalFCI_getNbhd`, p, node_names, adj, targets, verbose)
}

printS <- function(neighbors) {
    invisible(.Call(`_LocalFCI_printS`, neighbors))
}

getInitialValues <- function(neighbors, i, j) {
    .Call(`_LocalFCI_getInitialValues`, neighbors, i, j)
}

setListEmptySet <- function(neighbors, i, j) {
    .Call(`_LocalFCI_setListEmptySet`, neighbors, i, j)
}

setListEfficient <- function(neighbors, i, j, kvals) {
    .Call(`_LocalFCI_setListEfficient`, neighbors, i, j, kvals)
}

checkSeparationFunc <- function(neighbors, i, j, sep, val_to_check) {
    .Call(`_LocalFCI_checkSeparationFunc`, neighbors, i, j, sep, val_to_check)
}

checkSeparationFuncCorrected <- function(neighbors, i, j, sep, val_to_check) {
    .Call(`_LocalFCI_checkSeparationFuncCorrected`, neighbors, i, j, sep, val_to_check)
}

