# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rule1 <- function(G, track_changes, verbose = FALSE) {
    .Call(`_LocalFCI_rule1`, G, track_changes, verbose)
}

rule2 <- function(G, track_changes, verbose = FALSE) {
    .Call(`_LocalFCI_rule2`, G, track_changes, verbose)
}

rule3 <- function(G, track_changes, verbose = FALSE) {
    .Call(`_LocalFCI_rule3`, G, track_changes, verbose)
}

rule4 <- function(G, sepsets, neighborhood, track_changes, verbose = FALSE) {
    .Call(`_LocalFCI_rule4`, G, sepsets, neighborhood, track_changes, verbose)
}

rule8 <- function(G, track_changes, verbose = FALSE) {
    .Call(`_LocalFCI_rule8`, G, track_changes, verbose)
}

rule9 <- function(G, track_changes, verbose = FALSE) {
    .Call(`_LocalFCI_rule9`, G, track_changes, verbose)
}

rule10 <- function(G, track_changes, verbose = FALSE) {
    .Call(`_LocalFCI_rule10`, G, track_changes, verbose)
}

allRules <- function(G, sepsets, neighborhood, verbose) {
    invisible(.Call(`_LocalFCI_allRules`, G, sepsets, neighborhood, verbose))
}

minDiscPath <- function(pag, a, b, c, verbose = FALSE) {
    .Call(`_LocalFCI_minDiscPath`, pag, a, b, c, verbose)
}

minUncovPdPath <- function(p, G, alpha, beta, gamma, verbose) {
    .Call(`_LocalFCI_minUncovPdPath`, p, G, alpha, beta, gamma, verbose)
}

get_skeleton_total <- function(var_list, df, signif_level) {
    .Call(`_LocalFCI_get_skeleton_total`, var_list, df, signif_level)
}

get_skeleton_target <- function(var_list, target, df, signif_level = 0.05) {
    .Call(`_LocalFCI_get_skeleton_target`, var_list, target, df, signif_level)
}

fci <- function(true_dag, df, targets, names, lmax = 3L, signif_level = 0.05, verbose = TRUE) {
    .Call(`_LocalFCI_fci`, true_dag, df, targets, names, lmax, signif_level, verbose)
}

compare_skeletons <- function(est, truth, verbose) {
    .Call(`_LocalFCI_compare_skeletons`, est, truth, verbose)
}

compare_v_structures <- function(est, truth, verbose) {
    .Call(`_LocalFCI_compare_v_structures`, est, truth, verbose)
}

parent_recovery_accuracy <- function(est, truth, targets, verbose) {
    .Call(`_LocalFCI_parent_recovery_accuracy`, est, truth, targets, verbose)
}

convert_true_dag <- function(G) {
    .Call(`_LocalFCI_convert_true_dag`, G)
}

convert_pc_amat <- function(G) {
    .Call(`_LocalFCI_convert_pc_amat`, G)
}

all_metrics <- function(est, true_dag, cpdag, targets, verbose = FALSE) {
    .Call(`_LocalFCI_all_metrics`, est, true_dag, cpdag, targets, verbose)
}

neighborhood_metrics <- function(G) {
    .Call(`_LocalFCI_neighborhood_metrics`, G)
}

get_partial_correlation <- function(C, i, j, k) {
    .Call(`_LocalFCI_get_partial_correlation`, C, i, j, k)
}

fisherZ <- function(pc, n, k_size) {
    .Call(`_LocalFCI_fisherZ`, pc, n, k_size)
}

condIndTest <- function(C, i, j, k, n, signif_level) {
    .Call(`_LocalFCI_condIndTest`, C, i, j, k, n, signif_level)
}

get_current_edges <- function(i, p, graph) {
    .Call(`_LocalFCI_get_current_edges`, i, p, graph)
}

combn_cpp <- function(x, l) {
    .Call(`_LocalFCI_combn_cpp`, x, l)
}

get_neighbors_from_dag <- function(i, p, true_dag, verbose) {
    .Call(`_LocalFCI_get_neighbors_from_dag`, i, p, true_dag, verbose)
}

get_multiple_neighbors_from_dag <- function(targets, p, true_dag, verbose) {
    .Call(`_LocalFCI_get_multiple_neighbors_from_dag`, targets, p, true_dag, verbose)
}

create_conditioning_sets_efficient_cpp2 <- function(neighbors) {
    .Call(`_LocalFCI_create_conditioning_sets_efficient_cpp2`, neighbors)
}

fci_setup <- function(true_dag, targets, names, lmax, verbose) {
    .Call(`_LocalFCI_fci_setup`, true_dag, targets, names, lmax, verbose)
}

change_S_efficient <- function(S, i, j, sep) {
    invisible(.Call(`_LocalFCI_change_S_efficient`, S, i, j, sep))
}

change_S_0_efficient <- function(S, i, j) {
    invisible(.Call(`_LocalFCI_change_S_0_efficient`, S, i, j))
}

get_potential_sep <- function(i, j, neighborhood, p, true_dag) {
    .Call(`_LocalFCI_get_potential_sep`, i, j, neighborhood, p, true_dag)
}

check_separation_sample_efficient <- function(l, i, j, kvals, sep, true_dag, names, neighborhood, C, S, pval, num_tests, R, n, signif_level, verbose) {
    invisible(.Call(`_LocalFCI_check_separation_sample_efficient`, l, i, j, kvals, sep, true_dag, names, neighborhood, C, S, pval, num_tests, R, n, signif_level, verbose))
}

check_separation_sample_efficient_target <- function(l, i, j, kvals, sep, true_dag, names, neighborhood, C, S, pval, num_tests, R, n, signif_level, verbose) {
    invisible(.Call(`_LocalFCI_check_separation_sample_efficient_target`, l, i, j, kvals, sep, true_dag, names, neighborhood, C, S, pval, num_tests, R, n, signif_level, verbose))
}

makeFinalGraph <- function(G, C, neighborhood) {
    invisible(.Call(`_LocalFCI_makeFinalGraph`, G, C, neighborhood))
}

get_v_structures_efficient <- function(L) {
    .Call(`_LocalFCI_get_v_structures_efficient`, L)
}

